# Generated by Django 4.1.3 on 2023-06-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_employee_name_remove_employee_occupation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='body',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='created',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='updated',
        ),
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='occupation',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
